### PR TITLE
Added newsletter - issue#82

### PR DESCRIPTION
**Pull request by vansh1999**
Added Newsletter section on the website
-> designed newsletter

### CODE REVIEW

**Comment by lakshyatyagi24** [comment]
Please share the screenshot of it

**Comment by vansh1999** [comment]
Here is it
Screenshot from 2020-10-27 20-43-02

**Comment by lakshyatyagi24** [comment]
How we will access subscribed email id?

**Comment by lakshyatyagi24** [comment]
i am merging this you have to create new issue for this.

**Pull request merged**
