### PR TITLE
Fixed Screen-Overlay on header

### PR DESCRIPTION
**Pull request by chinmaym07**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
#129
## Type of change
Fixed Screen Overlay on  Header
- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Changes that were made, were static in nature so I just tested it locally

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

Screen Shot 2020-12-09 at 18 11 05
Screen Shot 2020-12-09 at 17 09 42

### CODE REVIEW

**Review by lakshyatyagi24 — APPROVED** [review]

**Comment by akanksha-raghav** [comment]
Steps to begin section overlay on a header and padding of registration section.

**Comment by chinmaym07** [comment]
Hey @akanksha-raghav I think I have to rectify this. 

can you please describe changes you require in above snap.

**Comment by chinmaym07** [comment]
Rectified this.

Screen Shot 2020-12-10 at 18 22 32

**Comment by chinmaym07** [comment]
Rectified this.

Screen Shot 2020-12-10 at 18 22 32
Screen Shot 2020-12-10 at 18 47 55

**Comment by akanksha-raghav** [comment]
@chinmaym07 yes

**Pull request merged**
