### PR TITLE
Search by clicking any tech stack #61

### LINKED ISSUE #61: Search by clicking any tech stack
image

On clicking any Tech stack it need to show all the projects based on that stack

### PR DESCRIPTION
**Pull request by PushpikaWan**
# Description
I added same filtering logic like searching to check to perform tech stack related searching. 

Fixes #61

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
I tested with happy paths and edge cases 

- [x] Test A

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by lakshyatyagi24** [comment]
Please resolve conflict

**Comment by lakshyatyagi24** [comment]
Issue is not solved it's not searching by clicking the tech stack please work on it

**Comment by PushpikaWan** [comment]
@lakshyatyagi24  It's filtering according to the clicked tech stack. do you want to update search input box as well?

**Comment by lakshyatyagi24** [comment]
it's working fine now but still there is an issue we don't have option to reset the filter. If you want you can create a new issue and leave or you can work on that feature and make PR

**Comment by lakshyatyagi24** [comment]
1 more issue is there On clicking ML it is also showing HTML tech stack projects.

**Comment by lakshyatyagi24** [comment]
> @lakshyatyagi24 It's filtering according to the clicked tech stack. do you want to update search input box as well?

No i think it's fine but if you have something good you are free to work on it

**Comment by PushpikaWan** [comment]
Cool. I think it's better to introduce that kind of reset there. You can create another issue for that with suggested UI changes. 
I'll fix this "clicking ML it is also showing HTML tech stack projects." issue here

**Comment by lakshyatyagi24** [comment]
yes

**Comment by PushpikaWan** [comment]
fixes added with this https://github.com/StudentCode-in/StudentCode-in.github.io/pull/72 and it has been merged..
Search by clicking any tech stack #61 #72

**Pull request merged**
