### PR TITLE
Add popup for Registration closed

### LINKED ISSUE #83: Popup required
In Registration section on clicking apply need a popup with text similar to "Registration Closed"

### PR DESCRIPTION
**Pull request by dhruvik-patel**
# Description
I have added a popup for registration closed. I have used a bootstrap modal for this.

Fixes #83 popup required.

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A : I have tested it on Google Chrome (version 86) and Microsoft Edge (version 86)

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by lakshyatyagi24** [comment]
Please attach screenshot or screen recording of output

**Comment by dhruvik-patel** [comment]
> Please attach screenshot or screen recording of output
Screenshot (1572)
Screenshot (1573)

**Comment by akanksha-raghav** [comment]
@dhruvik-patel kindly make this in the center rather than on the top and add some styling.

**Comment by dhruvik-patel** [comment]
Please check my recent commit. Here are some screenshots.
I have also checked it in Microsoft Edge.

Screenshot (1577)
Screenshot (1574)
Screenshot (1575)
Screenshot (1576)

**Review by akanksha-raghav — APPROVED** [review]

**Pull request merged**
