### PR TITLE
Improving timeline design

### LINKED ISSUE #84: Timeline design can be improved

### PR DESCRIPTION
**Pull request by zorione**
# Description

Improved the timeline design by adding animations to it.

Fixes #84

### CODE REVIEW

**Comment by zorione** [comment]
@lakshyatyagi24 Sir, kindly review the changes.

**Comment by lakshyatyagi24** [comment]
can you please attach a screenshot or screen recording of changes

**Comment by zorione** [comment]
Yeah Sure..

**Comment by zorione** [comment]
[Timeline changes.zip](https://github.com/StudentCode-in/StudentCode-in.github.io/files/5460960/Timeline.changes.zip)

@lakshyatyagi24 Sir, please go through the video.

**Review by lakshyatyagi24 — COMMENTED** [review]
approved

**Pull request merged**
